name: Update indieblog.goggle

permissions:
  contents: write
  
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up D
      uses: dlang-community/setup-dlang@v2
      with:
        compiler: dmd

    - name: Run dub
      run: dub run

    - name: Check for changes in indieblog.goggle
      id: check_changes
      run: |
        git diff --exit-code indieblog.goggle || echo "changed=true" >> $GITHUB_OUTPUT

    - name: Commit, push, and submit changes to Brave
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add indieblog.goggle
        git commit -m "[bot] Update indieblog.goggle"
        git push origin master

        # Wait a bit to make sure that the goggle will be publicly accessible
        sleep 10
        curl -X POST "https://search.brave.com/api/goggles/submit?url=https%3A%2F%2Fraw.githubusercontent.com%2FLorenDB%2Findieblog-goggle%2Frefs%2Fheads%2Fmaster%2Findieblog.goggle"
